"""
Harness loader: discovers and loads the 4 pluggable modules from a harness directory.

Each harness directory must contain:
  - memory.py    exporting MemoryStrategy
  - planning.py  exporting PlanningStrategy
  - action.py    exporting ActionStrategy
  - tool_policy.py exporting ToolPolicyStrategy
"""

import importlib
import importlib.resources
import logging
import sys
import types
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)

_REPO_ROOT = Path(__file__).resolve().parents[2]

# Where a harness can live, in lookup order. Runs install the harness they are
# about to execute -- generated by the meta model, or copied from a reference --
# into scripts/workspaces/<name>/, so that is checked first; a bare reference
# name also resolves to its source package, which makes a harness loadable in
# place for debugging.
HARNESS_ROOTS = (
    ("scripts.workspaces", _REPO_ROOT / "scripts" / "workspaces"),
    ("harness_factory.harnesses", _REPO_ROOT / "harness_factory" / "harnesses"),
)


# Checkpoints trained before the repository was reorganised emit
# ``from modular_agent.kernel.types import ...`` in the harnesses they write --
# that was the import path the generation prompt advertised at the time. Alias the
# three modules such a harness can name onto their current homes so its code
# still loads. Nothing in this repository imports these names.
_LEGACY_MODULE_ALIASES = {
    "modular_agent.kernel.types": "scripts.kernel.types",
    "modular_agent.kernel.protocols": "scripts.kernel.protocols",
    "modular_agent.models.base": "scripts.models.base",
}


def _install_legacy_aliases() -> None:
    """Register the pre-restructure module names in ``sys.modules``."""
    if "modular_agent" in sys.modules:
        return
    shim = types.ModuleType("modular_agent")
    shim.__path__ = []  # a package, so submodule imports resolve
    sys.modules["modular_agent"] = shim
    for legacy, current in _LEGACY_MODULE_ALIASES.items():
        parent_name, _, leaf = legacy.rpartition(".")
        if parent_name not in sys.modules:
            parent = types.ModuleType(parent_name)
            parent.__path__ = []
            sys.modules[parent_name] = parent
            setattr(sys.modules[parent_name.rpartition(".")[0]],
                    parent_name.rpartition(".")[2], parent)
        module = importlib.import_module(current)
        sys.modules[legacy] = module
        setattr(sys.modules[parent_name], leaf, module)


def _resolve_harness_package(harness_name: str) -> str:
    """Map a harness directory name onto its importable package path."""
    for package, root in HARNESS_ROOTS:
        if (root / harness_name / "memory.py").is_file():
            return f"{package}.{harness_name}"
    return f"{HARNESS_ROOTS[0][0]}.{harness_name}"


def _load_prompt_templates(base: str, harness_name: str) -> dict:
    """Load harness prompt templates from prompt.yaml at runtime."""
    prompt_path = importlib.resources.files(base).joinpath("prompt.yaml")
    if not prompt_path.is_file():
        return {}

    prompt_config = yaml.safe_load(prompt_path.read_text(encoding="utf-8")) or {}
    if not isinstance(prompt_config, dict):
        raise ImportError(
            f"Harness '{harness_name}' prompt.yaml must be a mapping."
        )
    return prompt_config


def load_harness(harness_name: str) -> dict:
    """Dynamically load a harness's 4 modules.

    Args:
        harness_name: Name of a harness directory under scripts/workspaces/
            (installed for this run) or harness_factory/harnesses/.

    Returns:
        dict with keys 'memory', 'planning', 'action', 'tool_policy',
        each containing an instantiated strategy object.
    """
    _install_legacy_aliases()
    base = _resolve_harness_package(harness_name)

    try:
        # Ensure repaired harness code is re-imported from disk each round.
        # Without this, Python may reuse cached modules from sys.modules.
        for mod_name in list(sys.modules.keys()):
            if mod_name == base or mod_name.startswith(f"{base}."):
                sys.modules.pop(mod_name, None)
        importlib.invalidate_caches()
        importlib.import_module(base)
        memory_mod = importlib.import_module(f"{base}.memory")
        planning_mod = importlib.import_module(f"{base}.planning")
        action_mod = importlib.import_module(f"{base}.action")
        tool_policy_mod = importlib.import_module(f"{base}.tool_policy")
    except ModuleNotFoundError as e:
        raise ImportError(
            f"Failed to load harness '{harness_name}'. "
            f"Ensure all 4 files exist under one of "
            f"{', '.join(str(root) for _, root in HARNESS_ROOTS)}. "
            f"Error: {e}"
        ) from e

    # Each module must export a class with the fixed name
    required_exports = {
        "memory": ("MemoryStrategy", memory_mod),
        "planning": ("PlanningStrategy", planning_mod),
        "action": ("ActionStrategy", action_mod),
        "tool_policy": ("ToolPolicyStrategy", tool_policy_mod),
    }

    # Optional harness-level prompt templates loaded at runtime from prompt.yaml
    prompts = _load_prompt_templates(base, harness_name)

    result = {}
    for key, (class_name, mod) in required_exports.items():
        if not hasattr(mod, class_name):
            raise ImportError(
                f"Harness '{harness_name}/{key}.py' must export a class named '{class_name}'."
            )
        cls = getattr(mod, class_name)
        try:
            # Preferred path: initialize component prompt store in __init__.
            result[key] = cls(prompts=prompts)
        except TypeError:
            # Compatibility fallback for components that don't accept prompts yet.
            result[key] = cls()
            setattr(result[key], "prompts", prompts)

    result["prompts"] = prompts

    logger.info(
        f"Loaded harness '{harness_name}': "
        f"memory={type(result['memory']).__name__}, "
        f"planning={type(result['planning']).__name__}, "
        f"action={type(result['action']).__name__}, "
        f"tool_policy={type(result['tool_policy']).__name__}"
    )
    return result
